# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f59eaa5580a5ba0926125c9c582c9750b2adc64cc27ed27201aed3d3da19258a22898df1ef07a0673ca984f9f86d0defc58e725d738c9deaeedfe424cc13e3f

test:
  secret_key_base: 2ea855cf48f51cef45953c341305e6149a868ddfc4f590748cb485f0738099c81f1361bce8d85b0778ac0b365b7bbb11044ee4cf6f1cb45cd995ccf7c0eae50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
